### ISSUE TITLE
No help or version for command opercmd

### ISSUE THREAD

**Issue by jacklotusho** [mikefultonbluemix/MVSCommand#9]
./opercmd -?
S0W1      2019056  11:29:34.40             ISF031I CONSOLE IBMUSER ACTIVATED
S0W1      2019056  11:29:34.40            --?
S0W1      2019056  11:29:34.40  STC04250   IEE305I -?       COMMAND INVALID

**Comment by mikefultonbluemix** [comment]
1/2 of the request has been implemented - the 'help' support. Can you open up a separate issue if you also want the version support in opercmd?

To determine if your MVSCommand package contains the fix for help, either issue:
   opercmd -? 
or issue: 
  mvscmd -b

If the build is newer than:
Build: 2019/03/01 00:32:03 CUT

then you have this fix. If you get the drop from JFrog, then get: BinTray Version: 201902281833 or newer
